name: sites

on:
  push:
    branches:
      - main
    paths:
      - 'sites/**'

jobs:
  publish-sites:
    name: Publish twake-chat.com site
    uses: ./.github/workflows/twake-chat-site-publish.yml
    secrets: inherit
