name: twake-chat.com docker build

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get all src files that have changed
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            packages/sites/twake-chat.com/**/*
            .github/workflows/**
      - name: Publish to dockerhub
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: linagora/twake-chat.com
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          workdir: "${{ github.workspace }}/sites/twake-chat.com"
          context: .
          buildoptions: "-t linagora/twake-chat.com -f Dockerfile"
          tags: "latest"
